# Generated by Django 5.2.16 on 2026-07-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'ORGANIZER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
        ),
    ]
