# Generated by Django 5.2.16 on 2026-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='طول دوره (ساعت)'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک تصویر دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته')], default='BEGINNER', max_length=20, verbose_name='سطح دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(default='ندارد', max_length=255, verbose_name='پیش\u200cنیازها'),
        ),
    ]
