# Generated by Django 5.2.16 on 2026-07-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_hours_course_image_url_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='تصویر دوره'),
        ),
    ]
