# Generated by Django 5.2.16 on 2026-07-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursestep_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس (Draft)'), ('PUBLISHED', 'منتشر شده (Published)'), ('CLOSED', 'ثبت\u200cنام بسته شده (Closed)'), ('FINISHED', 'به پایان رسیده (Finished)')], default='DRAFT', max_length=20, verbose_name='وضعیت رویداد'),
        ),
    ]
