# Generated by Django 5.2.16 on 2026-07-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.CreateModel(
            name='CourseAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_values', to='courses.attribute', verbose_name='ویژگی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_attributes', to='courses.course', verbose_name='رویداد')),
            ],
            options={
                'unique_together': {('course', 'attribute')},
            },
        ),
    ]
