# Generated by Django 5.2.16 on 2026-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_attribute_remove_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته')], default='BEGINNER', max_length=20, verbose_name='سطح دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پیش\u200cنیازها'),
        ),
    ]
