# Generated by Django 5.2.16 on 2026-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestep',
            name='scheduled_time',
            field=models.CharField(default='تعیین نشده', max_length=100, verbose_name='زمان برگزاری جلسه'),
        ),
        migrations.AddField(
            model_name='coursestep',
            name='speaker',
            field=models.CharField(default='مدرس دوره', max_length=255, verbose_name='سخنران / مربی / داور'),
        ),
    ]
